#
#  Makefile for GXemul src/components/machines
#

CXXFLAGS=$(CXXWARNINGS) $(CXXOPTIM) $(CPEDANTIC) $(INCLUDE2)
LIBS=$(OTHERLIBS)

OBJS=MachineComponent.o MVME88KMachine.o TestMIPSMachine.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

