#
#  Makefile for GXemul src/main/commands
#

CXXFLAGS=$(CXXFLAGSBASE) $(CPEDANTIC) $(XINCLUDE) $(INCLUDE2)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=AddComponentCommand.o CloseCommand.o ContinueCommand.o HelpCommand.o \
	LoadCommand.o ListComponentsCommand.o \
	QuitCommand.o RedoCommand.o RemoveComponentCommand.o \
	SaveCommand.o StatusCommand.o TreeCommand.o UndoCommand.o \
	VersionCommand.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

