#
#  Makefile for GXemul src/main/commands
#

CXXFLAGS=$(CXXWARNINGS) $(CXXOPTIM) $(CPEDANTIC) $(INCLUDE2)
LIBS=$(OTHERLIBS)

OBJS=AddComponentCommand.o CloseCommand.o ContinueCommand.o HelpCommand.o \
	LoadCommand.o ListComponentsCommand.o PauseCommand.o \
	QuitCommand.o RedoCommand.o RemoveComponentCommand.o ResetCommand.o \
	SaveCommand.o StatusCommand.o UndoCommand.o VersionCommand.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

