#
#  $Id: Makefile.skel,v 1.1 2007/12/31 11:50:19 debug Exp $
#
#  Makefile for GXemul src/ui/gtkmm
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE2)
CXXFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE2)

OBJS=DebugConsoleWidget.o EmulationDesignArea.o GtkmmUI.o GXemulWindow.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

