#
#  Makefile for GXemul src/ui/gtkmm
#

CXXFLAGS=$(CXXFLAGSBASE) $(CPEDANTIC) $(XINCLUDE) $(INCLUDE2)

OBJS=DebugConsoleWidget.o EmulationDesignArea.o GtkmmUI.o GXemulWindow.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

