#
#  $Id: Makefile.skel,v 1.2 2008/01/12 08:29:57 debug Exp $
#
#  Makefile for GXemul src/ui
#

all: do_console do_gtkmm do_nullui

$(OBJS): Makefile

do_console:
	cd console; $(MAKE)

do_gtkmm:
	cd gtkmm; $(MAKE)

do_nullui:
	cd nullui; $(MAKE)

clean:
	cd console; $(MAKE) clean
	cd gtkmm; $(MAKE) clean
	cd nullui; $(MAKE) clean
	rm -f $(OBJS) *core

clean_all: clean
	cd console; $(MAKE) clean_all
	cd gtkmm; $(MAKE) clean_all
	cd nullui; $(MAKE) clean_all
	rm -f Makefile

