#
#  $Id: Makefile.skel,v 1.3 2007-03-24 03:12:17 debug Exp $
#
#  Makefile for GXemul src/disk
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=bootblock.o bootblock_apple.o bootblock_iso9660.o \
	diskimage.o diskimage_scsicmd.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

