#
#  Makefile for GXemul src/ui/nullui
#

CXXFLAGS=$(CXXFLAGSBASE) $(CPEDANTIC) $(XINCLUDE) $(INCLUDE2)

OBJS=NullUI.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

