#
#  Makefile for GXemul src/components/cpu
#

CXXFLAGS=$(CXXWARNINGS) $(CXXOPTIM) $(CPEDANTIC) $(INCLUDE2)
LIBS=$(OTHERLIBS)

OBJS=CPUComponent.o MIPS_CPUComponent.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

