#
#  Makefile for GXemul src/main/actions
#

CXXFLAGS=$(CXXFLAGSBASE) $(CPEDANTIC) $(XINCLUDE) $(INCLUDE2)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=AddComponentAction.o ClearEmulationAction.o LoadEmulationAction.o \
	RemoveComponentAction.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

