#
#  Makefile for GXemul main
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(DINCLUDE) $(XINCLUDE)
CXXFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=emul.o emul_parse.o float_emul.o interrupt.o main.o memory.o misc.o \
	net.o settings.o timer.o useremul.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile


