#
#  Makefile for GXemul src/debugger
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugger.o debugger_expr.o

all: $(OBJS)

$(OBJS): Makefile

debugger.c: debugger_cmds.c

clean:
	rm -f $(OBJS) *core tmp_*.c

clean_all: clean
	rm -f Makefile

