#
#  Makefile for GXemul src/debugger
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)
CXXFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugger.o debugger_expr.o

all: $(OBJS)

$(OBJS): Makefile

debugger.cc: debugger_cmds.cc

clean:
	rm -f $(OBJS) *core tmp_*.*c

clean_all: clean
	rm -f Makefile

