#
#  Makefile for GXemul src/symbol
#
#  Symbol handling support.
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(INCLUDE1)

OBJS=symbol.o symbol_demangle.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

