#
#  Makefile for GXemul src/ir
#

CXXFLAGS=$(CXXFLAGSBASE) $(XINCLUDE) $(INCLUDE1)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=	IRBlockCache.o IRNativeAMD64.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

