#
#  Makefile for GXemul src/ir
#

CXXFLAGS=$(CXXWARNINGS) $(CXXOPTIM) $(CPEDANTIC) $(INCLUDE1)
LIBS=$(OTHERLIBS)

OBJS=	IRBlockCache.o IRNativeAMD64.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

