#
#  Makefile for GXemul src/ir
#

CXXFLAGS=$(CXXWARNINGS) $(CXXOPTIM) $(CPEDANTIC) $(INCLUDE1)
LIBS=$(OTHERLIBS)

OBJS=	IRBlockCache.o IRNativeAMD64.o

all: $(OBJS) IRNative.o

$(OBJS): Makefile

# Special case without CPEDANTIC, since C++ gives warnings when
# trying to call runtime generated code like this.
IRNative.o: IRNative.cc Makefile
	$(CXX) $(CXXWARNINGS) $(CXXOPTIM) $(INCLUDE1) IRNative.cc -c -o IRNative.o

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

