#
#  Makefile for GXemul src/console
#
#  This directory contains code that is related to console and framebuffer
#  handling.
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE1)

OBJS=console.o x11.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

