/*  gxemul: $Id: syscall_freebsd.h,v 1.1 2007-06-15 00:41:21 debug Exp $  */

#ifndef SYSCALL_FREEBSD_H
#define SYSCALL_FREEBSD_H


/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD: src/sys/sys/syscall.h,v 1.178.2.5 2006/10/10 13:47:59 rwatson Exp $
 * created from FreeBSD: src/sys/kern/syscalls.master,v 1.198.2.5 2006/10/10 13:19:47 rwatson Exp 
 */

#define	FREEBSD_SYS_syscall	0
#define	FREEBSD_SYS_exit	1
#define	FREEBSD_SYS_fork	2
#define	FREEBSD_SYS_read	3
#define	FREEBSD_SYS_write	4
#define	FREEBSD_SYS_open	5
#define	FREEBSD_SYS_close	6
#define	FREEBSD_SYS_wait4	7
				/* 8 is old creat */
#define	FREEBSD_SYS_link	9
#define	FREEBSD_SYS_unlink	10
				/* 11 is obsolete execv */
#define	FREEBSD_SYS_chdir	12
#define	FREEBSD_SYS_fchdir	13
#define	FREEBSD_SYS_mknod	14
#define	FREEBSD_SYS_chmod	15
#define	FREEBSD_SYS_chown	16
#define	FREEBSD_SYS_break	17
				/* 18 is old getfsstat */
				/* 19 is old lseek */
#define	FREEBSD_SYS_getpid	20
#define	FREEBSD_SYS_mount	21
#define	FREEBSD_SYS_unmount	22
#define	FREEBSD_SYS_setuid	23
#define	FREEBSD_SYS_getuid	24
#define	FREEBSD_SYS_geteuid	25
#define	FREEBSD_SYS_ptrace	26
#define	FREEBSD_SYS_recvmsg	27
#define	FREEBSD_SYS_sendmsg	28
#define	FREEBSD_SYS_recvfrom	29
#define	FREEBSD_SYS_accept	30
#define	FREEBSD_SYS_getpeername	31
#define	FREEBSD_SYS_getsockname	32
#define	FREEBSD_SYS_access	33
#define	FREEBSD_SYS_chflags	34
#define	FREEBSD_SYS_fchflags	35
#define	FREEBSD_SYS_sync	36
#define	FREEBSD_SYS_kill	37
				/* 38 is old stat */
#define	FREEBSD_SYS_getppid	39
				/* 40 is old lstat */
#define	FREEBSD_SYS_dup	41
#define	FREEBSD_SYS_pipe	42
#define	FREEBSD_SYS_getegid	43
#define	FREEBSD_SYS_profil	44
#define	FREEBSD_SYS_ktrace	45
				/* 46 is old sigaction */
#define	FREEBSD_SYS_getgid	47
				/* 48 is old sigprocmask */
#define	FREEBSD_SYS_getlogin	49
#define	FREEBSD_SYS_setlogin	50
#define	FREEBSD_SYS_acct	51
				/* 52 is old sigpending */
#define	FREEBSD_SYS_sigaltstack	53
#define	FREEBSD_SYS_ioctl	54
#define	FREEBSD_SYS_reboot	55
#define	FREEBSD_SYS_revoke	56
#define	FREEBSD_SYS_symlink	57
#define	FREEBSD_SYS_readlink	58
#define	FREEBSD_SYS_execve	59
#define	FREEBSD_SYS_umask	60
#define	FREEBSD_SYS_chroot	61
				/* 62 is old fstat */
				/* 63 is old getkerninfo */
				/* 64 is old getpagesize */
#define	FREEBSD_SYS_msync	65
#define	FREEBSD_SYS_vfork	66
				/* 67 is obsolete vread */
				/* 68 is obsolete vwrite */
#define	FREEBSD_SYS_sbrk	69
#define	FREEBSD_SYS_sstk	70
				/* 71 is old mmap */
#define	FREEBSD_SYS_vadvise	72
#define	FREEBSD_SYS_munmap	73
#define	FREEBSD_SYS_mprotect	74
#define	FREEBSD_SYS_madvise	75
				/* 76 is obsolete vhangup */
				/* 77 is obsolete vlimit */
#define	FREEBSD_SYS_mincore	78
#define	FREEBSD_SYS_getgroups	79
#define	FREEBSD_SYS_setgroups	80
#define	FREEBSD_SYS_getpgrp	81
#define	FREEBSD_SYS_setpgid	82
#define	FREEBSD_SYS_setitimer	83
				/* 84 is old wait */
#define	FREEBSD_SYS_swapon	85
#define	FREEBSD_SYS_getitimer	86
				/* 87 is old gethostname */
				/* 88 is old sethostname */
#define	FREEBSD_SYS_getdtablesize	89
#define	FREEBSD_SYS_dup2	90
#define	FREEBSD_SYS_fcntl	92
#define	FREEBSD_SYS_select	93
#define	FREEBSD_SYS_fsync	95
#define	FREEBSD_SYS_setpriority	96
#define	FREEBSD_SYS_socket	97
#define	FREEBSD_SYS_connect	98
				/* 99 is old accept */
#define	FREEBSD_SYS_getpriority	100
				/* 101 is old send */
				/* 102 is old recv */
				/* 103 is old sigreturn */
#define	FREEBSD_SYS_bind	104
#define	FREEBSD_SYS_setsockopt	105
#define	FREEBSD_SYS_listen	106
				/* 107 is obsolete vtimes */
				/* 108 is old sigvec */
				/* 109 is old sigblock */
				/* 110 is old sigsetmask */
				/* 111 is old sigsuspend */
				/* 112 is old sigstack */
				/* 113 is old recvmsg */
				/* 114 is old sendmsg */
				/* 115 is obsolete vtrace */
#define	FREEBSD_SYS_gettimeofday	116
#define	FREEBSD_SYS_getrusage	117
#define	FREEBSD_SYS_getsockopt	118
#define	FREEBSD_SYS_readv	120
#define	FREEBSD_SYS_writev	121
#define	FREEBSD_SYS_settimeofday	122
#define	FREEBSD_SYS_fchown	123
#define	FREEBSD_SYS_fchmod	124
				/* 125 is old recvfrom */
#define	FREEBSD_SYS_setreuid	126
#define	FREEBSD_SYS_setregid	127
#define	FREEBSD_SYS_rename	128
				/* 129 is old truncate */
				/* 130 is old ftruncate */
#define	FREEBSD_SYS_flock	131
#define	FREEBSD_SYS_mkfifo	132
#define	FREEBSD_SYS_sendto	133
#define	FREEBSD_SYS_shutdown	134
#define	FREEBSD_SYS_socketpair	135
#define	FREEBSD_SYS_mkdir	136
#define	FREEBSD_SYS_rmdir	137
#define	FREEBSD_SYS_utimes	138
				/* 139 is obsolete 4.2 sigreturn */
#define	FREEBSD_SYS_adjtime	140
				/* 141 is old getpeername */
				/* 142 is old gethostid */
				/* 143 is old sethostid */
				/* 144 is old getrlimit */
				/* 145 is old setrlimit */
				/* 146 is old killpg */
#define	FREEBSD_SYS_setsid	147
#define	FREEBSD_SYS_quotactl	148
				/* 149 is old quota */
				/* 150 is old getsockname */
#define	FREEBSD_SYS_nfssvc	155
				/* 156 is old getdirentries */
				/* 157 is old statfs */
				/* 158 is old fstatfs */
#define	FREEBSD_SYS_lgetfh	160
#define	FREEBSD_SYS_getfh	161
#define	FREEBSD_SYS_getdomainname	162
#define	FREEBSD_SYS_setdomainname	163
#define	FREEBSD_SYS_uname	164
#define	FREEBSD_SYS_sysarch	165
#define	FREEBSD_SYS_rtprio	166
#define	FREEBSD_SYS_semsys	169
#define	FREEBSD_SYS_msgsys	170
#define	FREEBSD_SYS_shmsys	171
#define	FREEBSD_SYS_pread	173
#define	FREEBSD_SYS_pwrite	174
#define	FREEBSD_SYS_ntp_adjtime	176
#define	FREEBSD_SYS_setgid	181
#define	FREEBSD_SYS_setegid	182
#define	FREEBSD_SYS_seteuid	183
#define	FREEBSD_SYS_stat	188
#define	FREEBSD_SYS_fstat	189
#define	FREEBSD_SYS_lstat	190
#define	FREEBSD_SYS_pathconf	191
#define	FREEBSD_SYS_fpathconf	192
#define	FREEBSD_SYS_getrlimit	194
#define	FREEBSD_SYS_setrlimit	195
#define	FREEBSD_SYS_getdirentries	196
#define	FREEBSD_SYS_mmap	197
#define	FREEBSD_SYS___syscall	198
#define	FREEBSD_SYS_lseek	199
#define	FREEBSD_SYS_truncate	200
#define	FREEBSD_SYS_ftruncate	201
#define	FREEBSD_SYS___sysctl	202
#define	FREEBSD_SYS_mlock	203
#define	FREEBSD_SYS_munlock	204
#define	FREEBSD_SYS_undelete	205
#define	FREEBSD_SYS_futimes	206
#define	FREEBSD_SYS_getpgid	207
#define	FREEBSD_SYS_poll	209
#define	FREEBSD_SYS___semctl	220
#define	FREEBSD_SYS_semget	221
#define	FREEBSD_SYS_semop	222
#define	FREEBSD_SYS_msgctl	224
#define	FREEBSD_SYS_msgget	225
#define	FREEBSD_SYS_msgsnd	226
#define	FREEBSD_SYS_msgrcv	227
#define	FREEBSD_SYS_shmat	228
#define	FREEBSD_SYS_shmctl	229
#define	FREEBSD_SYS_shmdt	230
#define	FREEBSD_SYS_shmget	231
#define	FREEBSD_SYS_clock_gettime	232
#define	FREEBSD_SYS_clock_settime	233
#define	FREEBSD_SYS_clock_getres	234
#define	FREEBSD_SYS_nanosleep	240
#define	FREEBSD_SYS_ntp_gettime	248
#define	FREEBSD_SYS_minherit	250
#define	FREEBSD_SYS_rfork	251
#define	FREEBSD_SYS_openbsd_poll	252
#define	FREEBSD_SYS_issetugid	253
#define	FREEBSD_SYS_lchown	254
#define	FREEBSD_SYS_getdents	272
#define	FREEBSD_SYS_lchmod	274
#define	FREEBSD_SYS_netbsd_lchown	275
#define	FREEBSD_SYS_lutimes	276
#define	FREEBSD_SYS_netbsd_msync	277
#define	FREEBSD_SYS_nstat	278
#define	FREEBSD_SYS_nfstat	279
#define	FREEBSD_SYS_nlstat	280
#define	FREEBSD_SYS_preadv	289
#define	FREEBSD_SYS_pwritev	290
				/* 297 is old fhstatfs */
#define	FREEBSD_SYS_fhopen	298
#define	FREEBSD_SYS_fhstat	299
#define	FREEBSD_SYS_modnext	300
#define	FREEBSD_SYS_modstat	301
#define	FREEBSD_SYS_modfnext	302
#define	FREEBSD_SYS_modfind	303
#define	FREEBSD_SYS_kldload	304
#define	FREEBSD_SYS_kldunload	305
#define	FREEBSD_SYS_kldfind	306
#define	FREEBSD_SYS_kldnext	307
#define	FREEBSD_SYS_kldstat	308
#define	FREEBSD_SYS_kldfirstmod	309
#define	FREEBSD_SYS_getsid	310
#define	FREEBSD_SYS_setresuid	311
#define	FREEBSD_SYS_setresgid	312
				/* 313 is obsolete signanosleep */
#define	FREEBSD_SYS_aio_return	314
#define	FREEBSD_SYS_aio_suspend	315
#define	FREEBSD_SYS_aio_cancel	316
#define	FREEBSD_SYS_aio_error	317
#define	FREEBSD_SYS_aio_read	318
#define	FREEBSD_SYS_aio_write	319
#define	FREEBSD_SYS_lio_listio	320
#define	FREEBSD_SYS_yield	321
				/* 322 is obsolete thr_sleep */
				/* 323 is obsolete thr_wakeup */
#define	FREEBSD_SYS_mlockall	324
#define	FREEBSD_SYS_munlockall	325
#define	FREEBSD_SYS___getcwd	326
#define	FREEBSD_SYS_sched_setparam	327
#define	FREEBSD_SYS_sched_getparam	328
#define	FREEBSD_SYS_sched_setscheduler	329
#define	FREEBSD_SYS_sched_getscheduler	330
#define	FREEBSD_SYS_sched_yield	331
#define	FREEBSD_SYS_sched_get_priority_max	332
#define	FREEBSD_SYS_sched_get_priority_min	333
#define	FREEBSD_SYS_sched_rr_get_interval	334
#define	FREEBSD_SYS_utrace	335
				/* 336 is old sendfile */
#define	FREEBSD_SYS_kldsym	337
#define	FREEBSD_SYS_jail	338
#define	FREEBSD_SYS_sigprocmask	340
#define	FREEBSD_SYS_sigsuspend	341
				/* 342 is old sigaction */
#define	FREEBSD_SYS_sigpending	343
				/* 344 is old sigreturn */
#define	FREEBSD_SYS_sigtimedwait	345
#define	FREEBSD_SYS_sigwaitinfo	346
#define	FREEBSD_SYS___acl_get_file	347
#define	FREEBSD_SYS___acl_set_file	348
#define	FREEBSD_SYS___acl_get_fd	349
#define	FREEBSD_SYS___acl_set_fd	350
#define	FREEBSD_SYS___acl_delete_file	351
#define	FREEBSD_SYS___acl_delete_fd	352
#define	FREEBSD_SYS___acl_aclcheck_file	353
#define	FREEBSD_SYS___acl_aclcheck_fd	354
#define	FREEBSD_SYS_extattrctl	355
#define	FREEBSD_SYS_extattr_set_file	356
#define	FREEBSD_SYS_extattr_get_file	357
#define	FREEBSD_SYS_extattr_delete_file	358
#define	FREEBSD_SYS_aio_waitcomplete	359
#define	FREEBSD_SYS_getresuid	360
#define	FREEBSD_SYS_getresgid	361
#define	FREEBSD_SYS_kqueue	362
#define	FREEBSD_SYS_kevent	363
#define	FREEBSD_SYS_extattr_set_fd	371
#define	FREEBSD_SYS_extattr_get_fd	372
#define	FREEBSD_SYS_extattr_delete_fd	373
#define	FREEBSD_SYS___setugid	374
#define	FREEBSD_SYS_nfsclnt	375
#define	FREEBSD_SYS_eaccess	376
#define	FREEBSD_SYS_nmount	378
#define	FREEBSD_SYS_kse_exit	379
#define	FREEBSD_SYS_kse_wakeup	380
#define	FREEBSD_SYS_kse_create	381
#define	FREEBSD_SYS_kse_thr_interrupt	382
#define	FREEBSD_SYS_kse_release	383
#define	FREEBSD_SYS___mac_get_proc	384
#define	FREEBSD_SYS___mac_set_proc	385
#define	FREEBSD_SYS___mac_get_fd	386
#define	FREEBSD_SYS___mac_get_file	387
#define	FREEBSD_SYS___mac_set_fd	388
#define	FREEBSD_SYS___mac_set_file	389
#define	FREEBSD_SYS_kenv	390
#define	FREEBSD_SYS_lchflags	391
#define	FREEBSD_SYS_uuidgen	392
#define	FREEBSD_SYS_sendfile	393
#define	FREEBSD_SYS_mac_syscall	394
#define	FREEBSD_SYS_getfsstat	395
#define	FREEBSD_SYS_statfs	396
#define	FREEBSD_SYS_fstatfs	397
#define	FREEBSD_SYS_fhstatfs	398
#define	FREEBSD_SYS_ksem_close	400
#define	FREEBSD_SYS_ksem_post	401
#define	FREEBSD_SYS_ksem_wait	402
#define	FREEBSD_SYS_ksem_trywait	403
#define	FREEBSD_SYS_ksem_init	404
#define	FREEBSD_SYS_ksem_open	405
#define	FREEBSD_SYS_ksem_unlink	406
#define	FREEBSD_SYS_ksem_getvalue	407
#define	FREEBSD_SYS_ksem_destroy	408
#define	FREEBSD_SYS___mac_get_pid	409
#define	FREEBSD_SYS___mac_get_link	410
#define	FREEBSD_SYS___mac_set_link	411
#define	FREEBSD_SYS_extattr_set_link	412
#define	FREEBSD_SYS_extattr_get_link	413
#define	FREEBSD_SYS_extattr_delete_link	414
#define	FREEBSD_SYS___mac_execve	415
#define	FREEBSD_SYS_sigaction	416
#define	FREEBSD_SYS_sigreturn	417
#define	FREEBSD_SYS_getcontext	421
#define	FREEBSD_SYS_setcontext	422
#define	FREEBSD_SYS_swapcontext	423
#define	FREEBSD_SYS_swapoff	424
#define	FREEBSD_SYS___acl_get_link	425
#define	FREEBSD_SYS___acl_set_link	426
#define	FREEBSD_SYS___acl_delete_link	427
#define	FREEBSD_SYS___acl_aclcheck_link	428
#define	FREEBSD_SYS_sigwait	429
#define	FREEBSD_SYS_thr_create	430
#define	FREEBSD_SYS_thr_exit	431
#define	FREEBSD_SYS_thr_self	432
#define	FREEBSD_SYS_thr_kill	433
#define	FREEBSD_SYS__umtx_lock	434
#define	FREEBSD_SYS__umtx_unlock	435
#define	FREEBSD_SYS_jail_attach	436
#define	FREEBSD_SYS_extattr_list_fd	437
#define	FREEBSD_SYS_extattr_list_file	438
#define	FREEBSD_SYS_extattr_list_link	439
#define	FREEBSD_SYS_kse_switchin	440
#define	FREEBSD_SYS_ksem_timedwait	441
#define	FREEBSD_SYS_thr_suspend	442
#define	FREEBSD_SYS_thr_wake	443
#define	FREEBSD_SYS_kldunloadf	444
#define	FREEBSD_SYS_audit	445
#define	FREEBSD_SYS_auditon	446
#define	FREEBSD_SYS_getauid	447
#define	FREEBSD_SYS_setauid	448
#define	FREEBSD_SYS_getaudit	449
#define	FREEBSD_SYS_setaudit	450
#define	FREEBSD_SYS_getaudit_addr	451
#define	FREEBSD_SYS_setaudit_addr	452
#define	FREEBSD_SYS_auditctl	453
#define	FREEBSD_SYS__umtx_op	454
#define	FREEBSD_SYS_thr_new	455
#define	FREEBSD_SYS_MAXSYSCALL	456


#endif	/*  SYSCALL_FREEBSD_H  */
